name: Circle CI Trigger Cron

on:
  schedule:
    - cron: '0 0,6,12,18 * * *'

env:
  CIRCLECI_TOKEN: ${{ secrets.CIRCLECI_TOKEN }}

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger MirrorBot on CircleCI
        run: |
          curl -X POST --url "https://circleci.com/api/v2/project/gh/HydrophilicOrgs/aisehikuchbhi/pipeline" --user "${CIRCLECI_TOKEN}:" --header "Content-Type: application/json" -d '{"branch":"main"}'
