version: 2.1
jobs:
  build:
    docker:
      - image: python:3.9-slim-buster
        auth:
          username: "$DOCKER_USERNAME"
          password: "$DOCKERHUB_TOKEN"
      - image: circleci/postgres:alpine
        auth:
          username: "$DOCKER_USERNAME"
          password: "$DOCKERHUB_TOKEN"
        environment:
          POSTGRES_PASSWORD: postgres
    # For Personal Use, 1 vCPU + 2GB RAM is enough
    resource_class: small
    environment:
      PORT: 8080
      WORKDIR: /app/
      GOOGLE_CHROME_DRIVER: /usr/bin/chromedriver
      GOOGLE_CHROME_BIN: /usr/bin/google-chrome-stable

    steps:
      - run:
          name: Git Auth
          command: |
            export GitHubMail GitHubName GITHUB_TOKEN
            apt-get update && \
            apt-get upgrade -y && \
            apt-get install -y git
            git config --global user.email "$GitHubMail"
            git config --global user.name "$GitHubName"
            git config --global credential.helper store
            git config --global color.ui true
     
      - run:
          name: Add App
          no_output_timeout: 285m
          command: | 
            export DEBIAN_FRONTEND=noninteractive
            apt -qq update && apt -qq upgrade -y && \
            apt -qq install -y --no-install-recommends \
            apt-utils \
            curl \
            git \
            gnupg2 \
            wget \
            unzip \
            tree
            
            apt-get install -y libappindicator1 fonts-liberation libasound2 libatk-bridge2.0-0 libatspi2.0-0 libgbm1 libgtk-3-0 libnspr4 libnss3
            apt-get -y install dbus-x11 xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic xfonts-scalable
            apt-get -y install libxss1 lsb-release xdg-utils
            mkdir -p /tmp/ && \
            cd /tmp/ && \
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
            dpkg -i ./google-chrome-stable_current_amd64.deb; apt -fqqy install && \
            rm ./google-chrome-stable_current_amd64.deb
            apt --fix-broken install
            
            mkdir -p /tmp/ && \
            cd /tmp/ && \
            wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip && \
            unzip /tmp/chromedriver.zip chromedriver -d /usr/bin/ && \
            rm /tmp/chromedriver.zip
            apt -qq update && apt -qq install -y --no-install-recommends \
            gcc python3-dev zlib1g-dev \
            apt-transport-https \
            build-essential coreutils jq pv \
            ffmpeg mediainfo \
            neofetch \
            p7zip-full \
            libfreetype6-dev libjpeg-dev libpng-dev libgif-dev libwebp-dev && \
            rm -rf /var/lib/apt/lists /var/cache/apt/archives /tmp/*
            
            git clone -b alpha https://github.com/HydrophobicEnd/Userge-X userbot
            cd userbot
            pip install -U setuptools wheel && \
            pip install --no-cache-dir -r requirements.txt
            curl -H "Authorization: token ${GITHUB_TOKEN}" -H "Accept: application/vnd.github.v3.raw" "https://raw.githubusercontent.com/HydrophilicOrgs/priv-vars/main/userge-config.env" > config.env        
            bash run
            
workflows:
  version: 2
  workstation:
    jobs:
      - build:
          context: vars-global
